# Change this line:
mod_id=examplemod
# To:
mod_id=rubymod

# Change this line:
mod_name=Example Mod
# To:
mod_name=Ruby Mod

# Change this line:
mod_license=All Rights Reserved
# To:
mod_license=MIT

# Change this line:
mod_version=1.0.0-1.21.1
# To (or keep it):
mod_version=1.0.0

# Change this line:
mod_group_id=com.example.examplemod
# To:
mod_group_id=com.example.rubymod

# Change this line:
mod_authors=YourNamesHere
# To:
mod_authors=YourName

# Change this line:
mod_description=Example mod description.\nNewline characters can be used and will be replaced properly.
# To:
mod_description=Adds ruby ore, tools, and armor to Minecraft!